// mockData.ts



// All Listing Items
export const LISTING_ITEMS = [
  {
    listerId: 'user0',
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=3036&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Dior Backless Evening Gown',
    category: 'Red Dress',
    size: 'US 7',
    rentalPrice: 20,
    retailPrice: 100,
    rating: 1.56,
    ratingCount: 12,
    description: "This is a fantastic item that will elevate your style to the next level. Crafted from the finest materials, this piece combines both comfort and fashion. Whether youre going out with friends or attending a formal, this is the perfect choice for any occasion."
  },
  {
    listerId: 'user0',
    imageUrl: 'https://images.unsplash.com/photo-1609840170480-4c440bcd5d8f?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Ralph Lauren Suit',
    category: 'Gray Suit',
    size: 'US 10',
    rentalPrice: 35,
    retailPrice: 200,
    rating: 3.76,
    ratingCount: 123,
    description: "Elevate your style with this impeccably tailored three-piece gray plaid suit, perfect for making a bold yet sophisticated statement. Crafted from premium fabric, the suit features a slim-fit blazer, matching waistcoat, and tapered trousers that highlight a modern silhouette while ensuring all-day comfort. The subtle plaid pattern adds a touch of classic elegance, while the crisp white dress shirt and brown textured tie create a refined contrast. Finished with polished brown leather oxford shoes and a sleek timepiece, this ensemble is ideal for formal events, business meetings, or upscale gatherings."
  },
  {
    listerId: 'user0',
    imageUrl: 'https://images.unsplash.com/photo-1720800835432-36f9f10e78b3?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Chanel Tweed Blazer',
    category: 'Blazer',
    size: 'US 4',
    rentalPrice: 25,
    retailPrice: 150,
    rating: 4.5,
    ratingCount: 45,
    description: "Iconic Chanel tweed blazer that adds effortless sophistication to any wardrobe. Tailored to perfection with delicate pearl buttons and a flattering silhouette, this blazer is perfect for business lunches or chic evening outings."
  },
  {
    listerId: 'user4',
    imageUrl: 'https://images.unsplash.com/photo-1484527273420-c598cb0601f8?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Prada Leather Handbag',
    category: 'Accessories',
    size: 'One Size',
    rentalPrice: 15,
    retailPrice: 300,
    rating: 4.92,
    ratingCount: 78,
    description: "This sleek Prada leather handbag is the epitome of elegance. With its minimalist design, gold hardware, and spacious interior, it's perfect for adding a touch of luxury to any outfit."
  },
  {
    listerId: 'user5',
    imageUrl: 'https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Gucci Floral Maxi Dress',
    category: 'Maxi Dress',
    size: 'US 6',
    rentalPrice: 30,
    retailPrice: 250,
    rating: 3.8,
    ratingCount: 58,
    description: "Step into the spotlight with this vibrant Gucci floral maxi dress. The flowing fabric and bold prints are perfect for summer weddings, garden parties, or any event where you want to stand out."
  },
  {
    listerId: 'user6',
    imageUrl: 'https://images.unsplash.com/photo-1730715145729-bf929994c328?q=80&w=1933&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Tom Ford Velvet Blazer',
    category: 'Formal Wear',
    size: 'US 8',
    rentalPrice: 40,
    retailPrice: 320,
    rating: 4.2,
    ratingCount: 34,
    description: "A luxurious Tom Ford velvet blazer that oozes sophistication. The rich texture and slim fit make it the perfect choice for black-tie events or high-profile gatherings."
  },
  {
    listerId: 'user7',
    imageUrl: 'https://images.unsplash.com/photo-1622079400125-5b6679552976?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Versace Sequin Cocktail Dress',
    category: 'Cocktail Dress',
    size: 'US 2',
    rentalPrice: 50,
    retailPrice: 400,
    rating: 4.9,
    ratingCount: 89,
    description: "Turn heads with this dazzling Versace sequin cocktail dress. Perfect for glitzy parties and upscale events, it features a flattering fit and a sparkle that won’t go unnoticed."
  },
  {
    listerId: 'user8',
    imageUrl: 'https://images.unsplash.com/photo-1722363497275-9e28fa9752b8?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Balenciaga Oversized Hoodie',
    category: 'Streetwear',
    size: 'US M',
    rentalPrice: 18,
    retailPrice: 120,
    rating: 3.4,
    ratingCount: 22,
    description: "This Balenciaga oversized hoodie combines streetwear edge with high-fashion comfort. Ideal for casual days out or cozy nights in, it brings a bold, effortless vibe to any look."
  },
  {
    listerId: 'user0',
    imageUrl: 'https://images.unsplash.com/photo-1584386450584-c6d766612a45?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Nike Air Force 1 Sneakers',
    category: 'Footwear',
    size: 'US 9',
    rentalPrice: 12,
    retailPrice: 90,
    rating: 4.1,
    ratingCount: 65,
    description: "Classic Nike Air Force 1 sneakers that never go out of style. Perfect for everyday wear, these kicks bring comfort and versatility to your wardrobe."
  },
  {
    listerId: 'user10',
    imageUrl: 'https://images.unsplash.com/photo-1566534335938-05f1f2949435?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    listing: 'Hermès Silk Scarf',
    category: 'Accessories',
    size: 'One Size',
    rentalPrice: 10,
    retailPrice: 250,
    rating: 4.75,
    ratingCount: 50,
    description: "Elegant and timeless, this Hermès silk scarf adds a pop of color and sophistication to any outfit. Whether worn around the neck, as a headscarf, or tied to a bag, it’s a versatile luxury piece."
  }
];

// Sample Users
export const SAMPLE_USERS = [
  {
    userId: 'user0',
    name: 'Johnny Apple',
    email: 'johnnyapple@gmail.com',
    followers: 54,
    following: 62,
    bio: 'Avid Texas fan looking to get rent out some clothes in my wardrobe.',
    username: 'texas.fan77',
    profileImage: 'https://randomuser.me/api/portraits/men/60.jpg',
    reviews: 15,
    userRating: 4.8,
    responseRate: 99,
  },
  {
    userId: 'user1',
    name: 'Alyssa Gray',
    username: 'alyssa.gray04',
    email: 'alyssag@gmail.com',
    followers: 34,
    following: 76,
    bio: 'Fashionista. Staying Classy. Always looking great.',
    profileImage: 'https://i.pinimg.com/736x/2f/dd/bb/2fddbbaacd7c5c9e725e2b5f62be8b5b.jpg',
    reviews: 15,
    userRating: 4.5,
    responseRate: 96,
  },
  {
    userId: 'user2',
    name: 'James Carter',
    username: 'james.carter21',
    email: 'jamesc21@gmail.com',
    followers: 50,
    following: 120,
    bio: 'Tech enthusiast and avid traveler. Always up for a challenge!',
    profileImage: 'https://randomuser.me/api/portraits/men/45.jpg',
    reviews: 22,
    userRating: 4.8,
    responseRate: 92,
  },
  {
    userId: 'user3',
    name: 'Sophia Martinez',
    username: 'sophia.mtz12',
    email: 'sophiam12@gmail.com',
    followers: 78,
    following: 95,
    bio: 'Coffee lover. Bookworm. Finding joy in the little things.',
    profileImage: 'https://randomuser.me/api/portraits/women/68.jpg',
    reviews: 30,
    userRating: 4.9,
    responseRate: 98,
  },
  {
    userId: 'user4',
    name: 'Liam Johnson',
    username: 'liam.johnson88',
    email: 'liamj88@gmail.com',
    followers: 40,
    following: 60,
    bio: 'Fitness junkie. Always chasing new goals and personal bests.',
    profileImage: 'https://randomuser.me/api/portraits/men/34.jpg',
    reviews: 12,
    userRating: 4.3,
    responseRate: 85,
  },
  {
    userId: 'user5',
    name: 'Emma Wilson',
    username: 'emma.wilson77',
    email: 'emmaw77@gmail.com',
    followers: 65,
    following: 110,
    bio: 'Passionate about photography and storytelling. Capturing life\'s moments.',
    profileImage: 'https://randomuser.me/api/portraits/women/50.jpg',
    reviews: 18,
    userRating: 4.7,
    responseRate: 91,
  },
  {
    userId: 'user6',
    name: 'Noah Brown',
    username: 'noah.brown05',
    email: 'noahb05@gmail.com',
    followers: 85,
    following: 90,
    bio: 'Lifelong learner. Exploring the world one step at a time.',
    profileImage: 'https://randomuser.me/api/portraits/men/15.jpg',
    reviews: 25,
    userRating: 4.6,
    responseRate: 94,
  },
  {
    userId: 'user7',
    name: 'Olivia Davis',
    username: 'olivia.davis24',
    email: 'oliviad24@gmail.com',
    followers: 120,
    following: 135,
    bio: 'Creative soul with a love for music, art, and adventure.',
    profileImage: 'https://randomuser.me/api/portraits/women/30.jpg',
    reviews: 40,
    userRating: 4.9,
    responseRate: 99,
  },
  {
    userId: 'user8',
    name: 'Mason Lee',
    username: 'mason.lee32',
    email: 'masonl32@gmail.com',
    followers: 33,
    following: 44,
    bio: 'Gamer. Tech geek. Always up for a good debate.',
    profileImage: 'https://randomuser.me/api/portraits/men/78.jpg',
    reviews: 8,
    userRating: 4.1,
    responseRate: 87,
  },
  {
    userId: 'user9',
    name: 'Isabella Thomas',
    username: 'isabella.thomas91',
    email: 'isabellat91@gmail.com',
    followers: 72,
    following: 89,
    bio: 'Nature enthusiast. Hiking, photography, and chasing sunsets.',
    profileImage: 'https://randomuser.me/api/portraits/women/90.jpg',
    reviews: 20,
    userRating: 4.4,
    responseRate: 93,
  },
  {
    userId: 'user10',
    name: 'Ethan Garcia',
    username: 'ethan.garcia09',
    email: 'ethang09@gmail.com',
    followers: 55,
    following: 70,
    bio: 'Sports fanatic. Living life one game at a time.',
    profileImage: 'https://randomuser.me/api/portraits/men/55.jpg',
    reviews: 14,
    userRating: 4.2,
    responseRate: 89,
  }
];


// Closet Items (ProfileScreen)
export const CLOSET_ITEMS = [
  {
    id: '1',
    imageUrl: 'https://images.unsplash.com/photo-1604014237744-df3c8f9305a8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    brand: 'Nike',
    name: 'Air Max 2021',
    size: 'Men’s 10.5',
    price: '$35 / day',
  },
  {
    id: '2',
    imageUrl: 'https://images.unsplash.com/photo-1618354691325-68baad1f3d50?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    brand: 'Levi’s',
    name: 'Denim Jacket',
    size: 'Medium',
    price: '$20 / day',
  },
];

// Explore Listings
export const EXPLORE_ITEMS = [
  {
    imageUrl: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    location: 'Saugerties, New York',
    subtitle: 'Featured in Architectural Digest Jan 13 – 18',
    price: '$1,014 night',
    rating: 4.88,
  },
  {
    imageUrl: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    location: 'Malibu, California',
    subtitle: 'Oceanfront Property Jan 20 – 25',
    price: '$2,200 night',
    rating: 4.95,
  },
];

// Rental Items
export const RENTAL_ITEMS = [
  {
    id: '1',
    imageUrl: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    brand: 'Nike',
    name: 'Air Max 2022',
    dateRange: 'Feb 10 – Feb 14, 2025',
  },
  {
    id: '2',
    imageUrl: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    brand: 'Levi’s',
    name: 'Vintage Denim Jacket',
    dateRange: 'Mar 01 – Mar 05, 2025',
  },
];
